const races = [
  "Human Male",
  "Human Female",
  "Dwarvish Male",
  "Dwarvish Female",
  "Elvish Male",
  "Elvish Female",
  "Halfling Male",
  "Halfling Female",
  "Draconic Male",
  "Draconic Female",
  "Drow Male",
  "Drow Female",
  "Orcish Male",
  "Orcish Female",
];